# \u5E94\u7528\u540D\u79F0
spring:
  application:
    name: server
# \u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
server:
  port: 8080


dubbo:
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: com.example.service
  protocol:
    name: dubbo
    port: 20881
  application:
    name: server-provider
    qos-enable: false
  consumer:
    check: false