spring:
  application:
    name: server
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080

dubbo:
  registry:
    address: nacos://localhost:8849
    check: true
  scan:
    base-packages: com.example
  protocol:
    name: dubbo
    port: -1
    dispatcher: message
  application:
    qos-enable: false
    name: server-provider
  provider:
    threadpool: cached
#  consumer:
#    check: false