# \u5E94\u7528\u540D\u79F0
spring:
  application:
    name: restful
server:
  port: 8080

dubbo:
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: com.example.controller
  protocol:
    name: dubbo
    port: 20881
  application:
    name: restful-consumer
    qos-enable: false
  consumer:
    check: false
